<a href="https://colab.research.google.com/github/rosh4github/eportfolio/blob/main/Unit07_Ex2_perceptron_AND_operator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Source:

Unit 7 - Machine Learning module - University of Essex Online (2024)

Gemini (2024) Gemini response to Roshni Kasturi. 2 November.

### Author: Dr Mike Lakoju, CardiffMet

![Screenshot%202021-01-24%20at%202.53.10%20pm.png](attachment:Screenshot%202021-01-24%20at%202.53.10%20pm.png)

### Import Library

In [ ]:
import numpy as np

### Define "Inputs, outputs and weights" as Numpy arrays

#### Inputs

In [ ]:
# Creating input values as a matrix not as a vector
inputs = np.array([[0,0], [0,1], [1,0], [1,1]])

In [ ]:
# Chcking the shape of the inputs

inputs.shape

(4, 2)

In [ ]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

#### Outputs

In [ ]:
outputs = np.array([0, 0, 0, 1])

In [ ]:
# Checking the shape of the outputs

outputs.shape

# output - (4,) # signifies a 1 dimensional array with 4 elements # it is a tuple representing the shape of the array

(4,)

In [ ]:
outputs

array([0, 0, 0, 1])

#### Weights

In [ ]:
# one weight for x1 and one for x2
weights = np.array([0.0, 0.0])

#### Learning Rate

In [ ]:
learning_rate = 0.1

## Step function

In [ ]:
# This is our Activation function

def step_function(sum):
  if (sum >= 1):
    #print(f'The Sum of Weights is Greater or equal to 1')
    return 1
  else:
        #print(f'The Sum of Weights is NOT > or = to 1')
        return 0

## Process Output

<b>We define a function that allows us to calculate/ process the output. The function accepts an instance of our data, then calculate the sum function using Numpy. Finally, we check the output by passing it through the "Step Function."</b>

In [ ]:
def cal_output(instance):
  sum_func = instance.dot(weights)
  return step_function(sum_func)

We pass it as alist in a numpy array ...

In [ ]:
# cal_output function designed to simulate a single neuron's calculation and activation
cal_output(np.array([[1,1]])) # [[1,1]] - input data - 2 dimensional array (matrix) with a single row containing values x=1 and x2=1

0

## Train

In [ ]:
# Check the number of outputs

len(outputs)

4

In [ ]:
# Checking the index of the input at postion 3 ..
# this is the last input value
inputs[3]

array([1, 1])

In [ ]:
inputs

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

<b>Note that:</b> usually, we will need to define the number of epochs, because we will never really get a value of zero when dealing with real-world data. However, for this small data, we will run the loop till we obtain zero error

In [ ]:
def train():
    #
    total_error_value = 1

    # While the total_error_value is not equal to zero. we are asumming that at the start of running our network there will be no zero
    while (total_error_value != 0):

        #making the total_error 0 so we can do other calculations
        total_error_value = 0

        #Looping into each row of the dataset (remember indexing in python starts at zero hence 0-3 which are 4 values)
        for i in range(len(outputs)):

            #Calculating predictions
            prediction = cal_output(inputs[i])

            print("Prediction is ", prediction)

            # Calculating the absolute value of the error
            error = abs(outputs[i] - prediction)

            print("Error is ", error)

            #Updating the error
            total_error_value += error

            print("Total error value in iteration is ", total_error_value)

            if error > 0:
                for j in range(len(weights)):

                    #updating the weights for x1 and x2
                    weights[j] = weights[j] + (learning_rate * inputs[i][j] * error) # [i][j] = row and column values but each representing current loop they are in.
                    print('Weight updated to: ' + str(weights[j]))

        print('Total error Value: ' + str(total_error_value))

In [ ]:
train()

Prediction is  0
Error is  0
Total error value in iteration is  0
Prediction is  0
Error is  0
Total error value in iteration is  0
Prediction is  0
Error is  0
Total error value in iteration is  0
Prediction is  0
Error is  1
Total error value in iteration is  1
Weight updated to: 0.1
Weight updated to: 0.1
Total error Value: 1
Prediction is  0
Error is  0
Total error value in iteration is  0
Prediction is  0
Error is  0
Total error value in iteration is  0
Prediction is  0
Error is  0
Total error value in iteration is  0
Prediction is  0
Error is  1
Total error value in iteration is  1
Weight updated to: 0.2
Weight updated to: 0.2
Total error Value: 1
Prediction is  0
Error is  0
Total error value in iteration is  0
Prediction is  0
Error is  0
Total error value in iteration is  0
Prediction is  0
Error is  0
Total error value in iteration is  0
Prediction is  0
Error is  1
Total error value in iteration is  1
Weight updated to: 0.30000000000000004
Weight updated to: 0.30000000000000

## Classification

In [ ]:
# Now we have the final weights that will be used to classify new instances of the data after training.

weights

array([0.5, 0.5])

In [ ]:
cal_output(np.array([2,5]))

1

In [ ]:
cal_output(np.array([5,2]))

1

In [ ]:
cal_output(np.array([0.3,0.2]))

0

In [ ]:
cal_output(np.array([1,1]))

1